web:
  image: nginx
  volumes:
    - ./sezaam.conf:/etc/nginx/conf.d/default.conf:ro
    - ./levels:/var/www/levels:ro
    - ./nginx-dirs:/var/www/html:ro
  command: [nginx-debug, '-g', 'daemon off;']
  ports:
  - 80:80
